
version: '3.7'

services:
    spring-boot:
        image: openjdk:8-jdk-alpine
        container_name: spring-boot
        ports:
            - "8080:8080"
        volumes:
            - ./target/spring-boot-docker-0.0.1-SNAPSHOT.jar:/app.jar
        command: ["java", "-jar", "/app.jar"]
        env_file:
          - .env
        depends_on:
            - mysql
        networks:
            - spring-boot-network
